import { ICustomer } from "../models/ICustomer";

export const customers: ICustomer[] = [
  {
    key: "slug-1",
    name: "John Brown",
    phone: "8(966)123-456-78",
    email: "test@test.ru",
    social: "https://www.instagram.com/",
    city: "New York",
  },
  {
    key: "slug-2",
    name: "Jim Green",
    phone: "8(922)123-456-78",
    email: "test@test.ru",
    social: "https://www.facebook.com/",
    city: "London",
  },
  {
    key: "slug-3",
    name: "Joe Black",
    phone: "8(937)123-456-78",
    email: "test@test.ru",
    social: "https://vk.com/",
    city: "Sidney",
  },
  {
    key: "slug-4",
    name: "Jim Red",
    phone: "8(945)123-456-78",
    email: "test@test.ru",
    social: "https://www.instagram.com/",
    city: "New York",
  },
  {
    key: "slug-5",
    name: "Jim Red",
    phone: "8(945)123-456-78",
    email: "test@test.ru",
    social: "https://ru.linkedin.com/",
    city: "New York",
  },
  {
    key: "slug-11",
    name: "John Brown",
    phone: "8(966)123-456-78",
    email: "test@test.ru",
    social: "https://www.facebook.com/",
    city: "New York",
  },
  {
    key: "slug-12",
    name: "Jim Green",
    phone: "8(922)123-456-78",
    email: "test@test.ru",
    social: "https://www.facebook.com/",
    city: "London",
  },
  {
    key: "slug-13",
    name: "Joe Black",
    phone: "8(937)123-456-78",
    email: "test@test.ru",
    social: "https://vk.com/",
    city: "Sidney",
  },
  {
    key: "slug-14",
    name: "Jim Red",
    phone: "8(945)123-456-78",
    email: "test@test.ru",
    social: "https://www.instagram.com/",
    city: "New York",
  },
  {
    key: "slug-15",
    name: "Jim Red",
    phone: "8(945)123-456-78",
    email: "test@test.ru",
    social: "https://vk.com/",
    city: "New York",
  },
  {
    key: "slug-16",
    name: "Jim Red",
    phone: "8(945)123-456-78",
    email: "test@test.ru",
    social: "https://ru.linkedin.com/",
    city: "New York",
  },
];
